### PR TITLE
fix subgrouping not working in CEL filters

### LINKED ISSUE #620: wrong response when using `()` and operators in filters
# Expected Behavior
The command or API call using `||` in filter should respect the OR operator. For example, on running this command
```
$ ./tkn-results records list default/results/- --insecure --filter="data_type==TASK_RUN && (data.spec.pipelineSpec.tasks[0].name=='hello'||data.metadata.name=='hell')" 
```
the response should only show TaskRuns that fulfill one or both other conditions. 

# Actual Behavior
```
$ ./tkn-results records list default/results/- --insecure --filter="data_type==TASK_RUN && (data.spec.pipelineSpec.tasks[0].name=='hello'||data.metadata.name=='hell')" 
Name                                                                                               Type                                    Start                                   Update
default/results/c030918c-b7ff-4fd9-bafb-56487c481aed/records/c030918c-b7ff-4fd9-bafb-56487c481aed  tekton.dev/v1beta1.PipelineRun          2023-09-22 19:27:06 +0530 IST           2023-09-22 19:27:31 +0530 IST
```
It seems the CEL converter is not respecting the `()` boundary. 

# Steps to Reproduce the Problem

1. Needs Tekton Results installation with some data in database
2. Run a command or send an API request involving brackets and operators.
3. Observe the response

## Additional 
_Reported by @karthikjeeyar_

### PR DESCRIPTION
**Pull request by avinal**
# Changes

- CEL to SQL interpreter was not respecting subgroups given in CEL
  expression
- this commit fixes the subgrouping by containing unary and binary
  operators in parentheses
- fixes #620

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you review them:

- [x] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [x] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] [Tested your changes locally](https://github.com/tektoncd/results/blob/main/docs/DEVELOPMENT.md) (if this is a code change)
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [x] Has a kind label. You can add a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [x] Release notes block below has been updated with any user-facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [ ] Release notes contain the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
fix subgroups not working in CEL filtering
```

### CODE REVIEW

**Review by khrm — COMMENTED** [review]
/retest-required

**Comment by avinal** [comment]
I was discussing with Sayan about adding more random tests to the cel2sql interpreter. We may look for a fuzzing test. Let's discuss this on WG call.

File: pkg/api/server/cel2sql/interpreter.go [hunk 1]
```diff
@@ -319,6 +321,8 @@ func (i *interpreter) interpretBinaryCallExpr(expr *exprpb.Expr) error {
 		sqlOperator = posgresqlConcatOperator
```
Comment (alan-ghelardi) [inline pkg/api/server/cel2sql/interpreter.go:321]: Not related to your changes, but there's a typo here.

Comment (avinal) [reply pkg/api/server/cel2sql/interpreter.go:321]: Thanks Alan, fixed it.

**Review by khrm — COMMENTED** [review]
/lgtm
