### PR TITLE
Fix: Error message for GetResult handler

### LINKED ISSUE #337: List invalid results error message
# Expected Behavior
Listing invalid results should just say `{"code":5, "message":"record not found", "details":[]}`

# Actual Behavior
Listing invalid results using rest gives massage
```
{"code":5, "message":"failed to query on database: rpc error: code = NotFound desc = record not found", "details":[]}
```

# Steps to Reproduce the Problem

1. Create a taskRun or pipelineRun
2. Fetch the invalid results using rest
```bash
curl -k https://localhost:8080/apis/results.tekton.dev/v1alpha2/parents/default/results/1ae36611-1rf1-7543-8211-h546h66j8872
```
4. 

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", 
  GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:51:43Z", 
  GoVersion:"go1.19.4", Compiler:"gc", Platform:"darwin/amd64"}

  Kustomize Version: v4.5.7

  Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", 
  GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-25T19:38:29Z", 
  GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/arm64"}
  ```

- Tekton Pipeline version:

  ```
  Client version: 0.24.1
  Pipeline version: v0.44.0
 ```

no

### PR DESCRIPTION
**Pull request by sayan-biswas**
Fixes #337

Fix error message for GetResult handler.

Current: Shows wrapped RPC error message
`{"code":5, "message":"failed to query on database: rpc error: code = NotFound desc = record not found", "details":[]}`

Expected: Standard message
`{"code":5, "message":"record not found", "details":[]}`

## Release Note

```release-note
Fix GetResult to return the standard "record not found" error if the database query does not find a result.
```

### CODE REVIEW

**Comment by alan-ghelardi** [comment]
🙈

**Review by khrm — COMMENTED** [review]
/approve

**Review by khrm — COMMENTED** [review]
/kind bug

**Review by avinal — APPROVED** [review]

File: pkg/api/server/v1alpha2/results.go [hunk 1]
```diff
@@ -285,8 +285,11 @@ func (s *Server) getFilteredPaginatedSortedResults(ctx context.Context, parent s
 
 func getResultByParentName(gdb *gorm.DB, parent, name string) (*db.Result, error) {
 	r := &db.Result{}
-	if err := errors.Wrap(gdb.Where(&db.Result{Parent: parent, Name: name}).First(r).Error); err != nil {
-		return nil, status.Errorf(status.Code(err), "failed to query on database: %v", err)
+	q := gdb.
+		Where(&db.Result{Parent: parent, Name: name}).
+		First(r)
+	if err := errors.Wrap(q.Error); err != nil {
+		return nil, err
```
Comment (adambkaplan) [inline pkg/api/server/v1alpha2/results.go:292]: Do we have a means of unit testing this error message?

Comment (adambkaplan) [reply pkg/api/server/v1alpha2/results.go:292]: @sayan-biswas bump on this question.

Comment (sayan-biswas) [reply pkg/api/server/v1alpha2/results.go:292]: This errors are actually returned from the gorm package. In this repo we only have a wrapper. Untill we have a predefined set of error messages for all the RPCs, we can't create unit test to check the message string.

**Comment by dibyom** [comment]
@adambkaplan ok to merge?

**Review by adambkaplan — APPROVED** [review]
/lgtm

Added a release note - bug fixes should have release notes.
