### PR TITLE
[CLI] Fix the broken flags

### LINKED ISSUE #567: tkn-results CLI flags are broken, unknown flag error
# Expected Behavior

`tkn-results` should not show errors for existing flags
# Actual Behavior
`tkn-results` shows unknown flag error

image

# Steps to Reproduce the Problem

1. Checkout the latest main branch 3e249c3315b2eba9c14523372ff7a4d6ea6a2cdd
2. Build `tkn-results`
3. Configure `tkn-results` config
4. Run a command with flags `tkn-results list default --filter="summary.type=TASK_RUN"`

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```yaml
    clientVersion:
      buildDate: "2023-07-19T12:20:54Z"
      compiler: gc
      gitCommit: fa3d7990104d7c1f16943a67f11b154b71f6a132
      gitTreeState: clean
      gitVersion: v1.27.4
      goVersion: go1.20.6
      major: "1"
      minor: "27"
      platform: linux/amd64
    kustomizeVersion: v5.0.1
    serverVersion:
      buildDate: "2022-10-25T19:35:11Z"
      compiler: gc
      gitCommit: 434bfd82814af038ad94d62ebe59b133fcb50506
      gitTreeState: clean
      gitVersion: v1.25.3
      goVersion: go1.19.2
      major: "1"
      minor: "25"
      platform: linux/amd64
  ```

- Tekton Pipeline version: v0.47.2

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

# Additional Info
Likely caused by #461

### PR DESCRIPTION
**Pull request by khrm**
Earlier, we weren't calling getconfig in the beginning. After we added port-forward, we added the GetConfig call earlier. This fixed the global flag and when we merge the global flag fix, it broke the local flag. Now, refactored the setting flag/config to singleton in the init to avoid undefined scenarios.

Fixes #567

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you review them:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [x] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] [Tested your changes locally](https://github.com/tektoncd/results/blob/main/docs/DEVELOPMENT.md) (if this is a code change)
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [x] Has a kind label. You can add a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [ ] Release notes block below has been updated with any user-facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [ ] Release notes contain the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by khrm — COMMENTED** [review]
/kind bug

**Comment by khrm** [comment]
@avinal @sayan-biswas @enarha Let's get this merge asap.

File: tools/tkn-results/internal/config/config.go [hunk 1]
```diff
@@ -55,19 +56,20 @@ func init() {
 	viper.SetConfigName("results")
 	viper.SetConfigType("yaml")
 	viper.AddConfigPath("$HOME/.config/tkn")
-	pflag.StringP("addr", "a", "", "Result API server address")
-	pflag.StringP("authtoken", "t", "", "authorization bearer token to use for authenticated requests")
-	pflag.Parse()
+	err := setConfig()
+	if err != nil {
+		fmt.Println("error setting up flags and config", err)
```
Comment (enarha) [inline tools/tkn-results/internal/config/config.go:61]: Why don't we `os.Exit(1)` here?

File: tools/tkn-results/internal/config/config.go [hunk 2]
```diff
@@ -55,19 +56,20 @@ func init() {
...
+	}
 }
 
-func GetConfig() (*Config, error) {
+func setConfig() error {
 	if err := viper.BindPFlags(pflag.CommandLine); err != nil {
-		return nil, err
+		fmt.Println(err)
```
Comment (enarha) [inline tools/tkn-results/internal/config/config.go:67]: Why don't we return err here?

Comment (khrm) [reply tools/tkn-results/internal/config/config.go:67]: I forgot to update this. It should be fmt.Fatal

File: tools/tkn-results/internal/config/config.go (hunk 1 above)
Comment (khrm) [reply tools/tkn-results/internal/config/config.go]: I will update with log.Fatal.  Forgot to put it here.

File: tools/tkn-results/internal/config/config.go (hunk 2 above)
Comment (khrm) [reply tools/tkn-results/internal/config/config.go]: Actually, we should only return err here and do log.Fatal in init function.

File: tools/tkn-results/internal/config/config.go (hunk 1 above)
Comment (khrm) [reply tools/tkn-results/internal/config/config.go]: Fixed.

**Comment by avinal** [comment]
Tested! Resolves the issue, but I am noticing a new problem that was not present before. 
```
$ ./tkn-results list default --filter="summary.status=='SUCCESS'"    
ListResults: rpc error: code = InvalidArgument desc = error compiling CEL filters: ERROR: <input>:1:15: found no matching overload for '_==_' applied to '(int, string)'
 | summary.status=='SUCCESS'
 | ..............^
Error: rpc error: code = InvalidArgument desc = error compiling CEL filters: ERROR: <input>:1:15: found no matching overload for '_==_' applied to '(int, string)'
 | summary.status=='SUCCESS'
 | ..............^
 ```
 I am uncertain if this is related, if someone else is also getting the same error, this will need to be fixed as well.

**Comment by khrm** [comment]
@avinal 

Can you test with these commits:
https://github.com/tektoncd/results/commit/3643dcc5356f467d447c2cc6c567bc9f4569c98a
https://github.com/tektoncd/results/commit/89ee88eb8fdc9e767af3bfab0367ff175ef6b5c9

Is that error present in both of the revision?

**Comment by avinal** [comment]
Yes, it is present in both of them.

**Comment by avinal** [comment]
Ah sorry I was just checking the tkn-results, I need to check by re deploying the whole project. Let me do that

**Comment by khrm** [comment]
Is it happening with only this filter or every filter?

**Comment by khrm** [comment]
Is it happening with only this filter or every filter? @avinal

**Comment by khrm** [comment]
I created another issue regarding this. https://github.com/tektoncd/results/issues/569  This pr doesn't cause this issue and it should be tackled separately.

**Comment by avinal** [comment]
Only happening with this particular filter expression. All other I tested are working fine. It seems somehow the `summary.status` field is interpreted as int.

**Comment by avinal** [comment]
We are good to go with this PR then.
/approve

**Comment by enarha** [comment]
/approve
on behalf of @avinal
